id: proposit-core
connected-projects:
    parent:
        proposit-app: ..
work:
    path: /Users/brian/Projects/proposit-orchestration/docs/proposit-core/work
    tags:
        - bug
        - product
